name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master  # or main, depending on your repo

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Or the version your app requires

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Optional, used for PR comments
          action: "upload"
          app_location: "/"                         # Root folder of your app
          output_location: "build"                  # Build output folder (for React, it's "build")
